#!/bin/sh

# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e

# Must be a valid filename
NAME=shutter
PIDFILE=/tmp/$NAME.pid
#This is the command to be run, give the full pathname
DAEMON=/home/behrens/bin/shutter.py

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
        shift
	DAEMON_OPTS=$@
        
        echo -n "Starting daemon: $NAME with $DAEMON_OPTS"
	start-stop-daemon --start --pidfile $PIDFILE --startas $DAEMON -- $DAEMON_OPTS
        echo "."
	;;
  stop)
        echo -n "Stopping daemon: "$NAME
	start-stop-daemon --stop --oknodo --pidfile $PIDFILE
        echo "."
	;;
  *)
	echo "Usage: "$1" {start|stop}"
	exit 1
esac

exit 0





